### ISSUE TITLE
Notes on HTML

### ISSUE THREAD

**Issue by SidTheEngineer** [CasOlckers/prj-rev-bwfs-dasmoto#1]
Overall nice work with your HTML 👍. Syntax/formatting look good, including indentation. I've highlighted a couple of small areas for improvement below:

**Using the & sign**
In HTML, the "&" sign is a reserved symbol (meaning it is used for something other than text). In order to properly display the ampersand without any issues, we should use `&amp;`

**Using classes**
Right now, we have a lot of id's on elements that are styled similarly in the CSS (`h2brushes`, `h3brushes`, `h2paint` ...). We can instead take advantage of using a single class for this, and using id's to differentiate the different colors that we need to display (`#mediumspinggreen`, `#lightcoral`, `#skyblue`). In this way, we decrease the number of id's we need to worry about, making us less likely to repeat ourselves.

**Comment by CasOlckers** [comment]
Thanks for the feedback. I will work on making use of the classes and IDs more effectively.
